### ISSUE TITLE
iShowcase detail label text not visible completely and long text gets cut

### ISSUE THREAD

**Issue by Shayeeb** [rahuliyer95/iShowcase#10]
Hi, i have the latest iteration of iShowCase i.e 2.1 but sometimes the detail text doesn't show up completely.Long text gets cut at ends.Please look into the issue.It was working fine with swift 2.3 but after updating to swift 3 the issue crept in.Below is the screenshot of the issue and code as well:-
![screen shot 2016-11-07 at 4 06 06 pm](https://cloud.githubusercontent.com/assets/22047032/20054735/2542feee-a504-11e6-9d02-e75a162fbe0a.png)
![screen shot 2016-11-07 at 4 10 58 pm](https://cloud.githubusercontent.com/assets/22047032/20054918/e1706372-a504-11e6-95bd-bdf4db1fa0fc.png)
![screen shot 2016-11-07 at 4 11 20 pm](https://cloud.githubusercontent.com/assets/22047032/20054920/e2e4d36e-a504-11e6-96cf-32ab12476f43.png)

**Comment by nickoffff** [comment]
I have the same issue if the view is inside a UITabBarController.

**Comment by nickoffff** [comment]
I have the same issue. Long text is not breaked to new line.
