### ISSUE TITLE
Long labels are truncated

### ISSUE THREAD

**Issue by nickoffff** [rahuliyer95/iShowcase#11]
In version 2.1 long label was not broken to new line. It was possible to overcome this with manually added new lines. But after the last update (2.2) long labels are simply truncated.

**Comment by rahuliyer95** [comment]
Can you please share a screenshot

**Comment by rahuliyer95** [comment]
This is what I got on testing with the iPhone 7 Plus simulator

![simulator screen shot 09-dec-2016 7 41 04 pm](https://cloud.githubusercontent.com/assets/4255590/21051685/81d45c14-be47-11e6-975f-173176d5344d.png)

**Comment by nickoffff** [comment]
This is what I have on iPhone 5s.

![img_0059](https://cloud.githubusercontent.com/assets/18011494/21051840/55109c76-be22-11e6-80b4-afbc959a8adf.PNG)

**Comment by rahuliyer95** [comment]
What is the complete sentence for "You can delete an answer..." ?

**Comment by nickoffff** [comment]
The first one is: "Delete your answer". The second one is "You can delete an answer if you don't like it".
