### ISSUE TITLE
setUserInteractionEnabled NO

### ISSUE THREAD

**Issue by walsh2000** [rahuliyer95/iShowcase#3]
Hello

Is it necessary to set user interaction enabled to NO then to YES?
I'm concerned that setting user interaction to YES for every view in the hierarchy may be a mistake.

In the example app, the iShowcase view is on top and appears to have user interaction enabled, so it should soak up taps.
Was there a reason to flip all views to user interaction YES every time?

Thank you for your time

**Comment by rahuliyer95** [comment]
In testing I found that touch is recognized by views hidden by the background. If you can confirm that its not needed, I will remove it.
