### ISSUE TITLE
Using swift version, cannot change background color

### ISSUE THREAD

**Issue by cristinalopes** [rahuliyer95/iShowcase#7]
On objective-c version, it works fine, but in swift version, changing the background color doesn't work as expected. One possible fix is by creating a new background color property (for instance "coverColor") and use this color to fill the screen, instead of using the background color. And use this new property in the inicialization, keeping the background color always "clearColor". 

Other improvementswould be to create a property to configure the alpha to be applied instead of always being 0.75.

**Comment by rahuliyer95** [comment]
Have tried setting the `backgroundColor` property as shown in the example for the custom iShowcase? I tried with the example application and it was working

**Comment by rahuliyer95** [comment]
Please check the `rotation-support` branch
